version: '3.6'

name: 'your-project-name'

volumes:
  aws-profile:
    driver: local
  cdk-store:
    driver: local

services:
  sh:
    image: ghcr.io/nojimage/docker-cdk:2
    volumes:
      - aws-profile:/root/.aws
      - cdk-store:/root/.cdk
      - ./:/var/stack
    environment:
      IN_DOCKER: 1
