name: 'your-project-name'

volumes:
  aws-profile:
    driver: local
  cdk-store:
    driver: local

services:
  sh:
    image: ghcr.io/nojimage/docker-cdk:2.22
    volumes:
      - aws-profile:/root/.aws
      - cdk-store:/root/.cdk
      - ./:/var/stack
    environment:
      IN_DOCKER: 1
      # If you want to disable telemetry, please enable the `CDK_DISABLE_CLI_TELEMETRY` environment variable.
      # See: https://docs.aws.amazon.com/cdk/v2/guide/cli-telemetry.html
      # CDK_DISABLE_CLI_TELEMETRY: true
